- name: Tutorial 12
  hosts: localhost
  tasks:
    - name: Task 1 - Example task for Tutorial 12
      debug:
        msg: "Task 1 executed successfully for Tutorial 12"

    - name: Task 2 - Example task for Tutorial 12
      debug:
        msg: "Task 2 executed successfully for Tutorial 12"
